### ISSUE TITLE
Sort the list of books by author and/or title

### ISSUE THREAD

**Issue by olsen601** [olsen601/book_wishlist#7]
Currently books are sorted by ID, which correlates to date added; as that is how they are created. 

Would it be more user-friendly to sort by author, and/or title, or give the user a choice?  Implement what you think would be most useful.

**Comment by us0173ol** [comment]
for now  the sort feature is built in to the view list feature, so you get an option as soon as you choose to  view read or unread books.  If we get everything finished in time we could add a choice to sort in ascending or descending order, by id, or by date read.
